name: SY Panorama Workflow
label: SY Panorama on AWS
description: |
  Panorama on AWS Workflow

type: workflow

labels:
  collection:
    - SY Skillets

snippets:
  - name: SY Panorama on AWS
  - name: SY Capture Output for IP
  - name: SY Configure Panorama
