name: SY Capture Output for IP

label: SY Capture Panorama IP

description: |
  Capture the Panorama IP details from Terraform

type: python3

labels:
  collection:
    - SY Modules

# These two hidden variables are passed to the Python script and ultimately to Terraform
variables:
  - name: AWS_ACCESS_KEY_ID
    description: ID
    default:
    type_hint: hidden
  - name: AWS_SECRET_ACCESS_KEY
    description: Secret
    default:
    type_hint: hidden

# This uses output capturing to get values from the output and set them in the users session. Each subsequent skillet
# will have access to the captured_username and captured_secret variables from below.
snippets:
  - name: script
    file: output_capture.py
    input_type: env
    output_type: json
    outputs:
      - name: Panorama_IP
        capture_pattern: 'Primary_IP'
      - name: Secondary_IP
        capture_pattern: 'Secondary_IP'
      - name: Primary_Private_IP
        capture_pattern: 'Primary_Private_IP'
      - name: Secondary_Private_IP
        capture_pattern: 'Secondary_Private_IP'
